const moveList = {
  tackle: {
    moveName: "TACKLE",
    type: "normal",
    category: "physical",
    movePP: 35,
    moveMaxPP: 35,
    power: 40,
    accuracy: 1,
  },
  vineWhip: {
    moveName: "VINE WHIP",
    type: "grass",
    category: "physical",
    movePP: 25,
    moveMaxPP: 25,
    power: 45,
    accuracy: 1,
  },
  growl: {
    moveName: "GROWL",
    type: "normal",
    category: "status",
    movePP: 40,
    moveMaxPP: 40,
    power: 0,
    accuracy: 1,
    effect: "op att d1",
  },
  poisonPowder: {
    moveName: "POISON POWDER",
    type: "poison",
    category: "status",
    movePP: 35,
    moveMaxPP: 35,
    power: 0,
    accuracy: 0.75,
    effect: "poison",
  },
  bubble: {
    moveName: "BUBBLE",
    type: "water",
    category: "special",
    movePP: 30,
    moveMaxPP: 30,
    power: 40,
    accuracy: 1,
  },
  tailWhip: {
    moveName: "TAIL WHIP",
    type: "normal",
    category: "status",
    movePP: 30,
    moveMaxPP: 30,
    power: 0,
    accuracy: 1,
    effect: "op def d1",
  },
  withdraw: {
    moveName: "WITHDRAW",
    type: "water",
    category: "status",
    movePP: 40,
    moveMaxPP: 40,
    power: 0,
    accuracy: 1,
    effect: "me def u1",
  },
  scratch: {
    moveName: "SCRATCH",
    type: "normal",
    category: "physical",
    movePP: 35,
    moveMaxPP: 35,
    power: 40,
    accuracy: 1,
  },
  ember: {
    moveName: "EMBER",
    type: "fire",
    category: "special",
    movePP: 25,
    moveMaxPP: 25,
    power: 40,
    accuracy: 1,
  },
  willOWisp: {
    moveName: "WILL-O-WISP",
    type: "fire",
    category: "status",
    movePP: 15,
    moveMaxPP: 15,
    power: 0,
    accuracy: 0.85,
    effect: "burn",
  },
};

module.exports = moveList;
